<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVYW41rN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVYW41rN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVYW41rN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVYW41rN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVYW41rN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VYW41rN',
    'container.build_id' => '4eaadda1',
    'container.build_time' => 1616095224,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVYW41rN');
