<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container02SYXLj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container02SYXLj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container02SYXLj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container02SYXLj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container02SYXLj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '02SYXLj',
    'container.build_id' => 'b3276b70',
    'container.build_time' => 1616235925,
], __DIR__.\DIRECTORY_SEPARATOR.'Container02SYXLj');
