<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkiC26N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkiC26N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPkiC26N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPkiC26N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPkiC26N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PkiC26N',
    'container.build_id' => 'd0969919',
    'container.build_time' => 1616404884,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkiC26N');
